#!/usr/bin/env bash

cd $(dirname $0)/../../

if [ ! -f local-php-security-checker ]
then
  curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest | grep -E "browser_download_url(.+)linux_386" | cut -d : -f 2,3 | tr -d \\\" | xargs -I{} curl -L --output local-php-security-checker {} \
    && chmod +x local-php-security-checker;
fi

./local-php-security-checker
