services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    test.StepupReadId\Application\ReadySession\GetReadySessionQueryHandler: '@StepupReadId\Application\ReadySession\GetReadySessionQueryHandler'
    test.StepupReadId\Application\Session\RegisterSessionCommandHandler: '@StepupReadId\Application\Session\RegisterSessionCommandHandler'
    test.StepupReadId\Infrastructure\Services\ReadySession\ReadySessionStateHandler: '@StepupReadId\Infrastructure\Services\ReadySession\ReadySessionStateHandler'
    test.Symfony\Contracts\HttpClient\HttpClientInterface: '@Symfony\Contracts\HttpClient\HttpClientInterface'
